source 'https://rubygems.org'

gem 'rodakase', '0.0.1'

gem 'dry-configurable', '0.7.0'
gem 'dry-container', '0.7.2'   # ← updated from 0.6.0
gem 'dry-system', '0.12.0'
gem 'dry-auto_inject', '0.8.0'
